type RsethIslandHolder @entity
{
  id:                           ID!
  address:                      String!
  islandAmt:                    BigInt!
}

type RsethYTHolder @entity
{
  id:                           ID!
  address:                      String!
  ytAmt:                        BigInt!
}

type RsethIslandBalances @entity
{
  id:                           ID!
  balance0:                     BigInt!
  balance1:                     BigInt!
}

type UnibtcIslandHolder @entity
{
  id:                           ID!
  address:                      String!
  islandAmt:                    BigInt!
}

type UnibtcYTHolder @entity
{
  id:                           ID!
  address:                      String!
  ytAmt:                        BigInt!
}

type UnibtcIslandBalances @entity
{
  id:                           ID!
  balance0:                     BigInt!
  balance1:                     BigInt!
}

type SolvbtcIslandHolder @entity
{
  id:                           ID!
  address:                      String!
  islandAmt:                    BigInt!
}

type SolvbtcYTHolder @entity
{
  id:                           ID!
  address:                      String!
  ytAmt:                        BigInt!
}

type SolvbtcIslandBalances @entity
{
  id:                           ID!
  balance0:                     BigInt!
  balance1:                     BigInt!
}

type RusdVaultHolder @entity
{
  id:                           ID!
  address:                      String!
  vaultAmt:                     BigInt!
}

type RusdYTHolder @entity
{
  id:                           ID!
  address:                      String!
  ytAmt:                        BigInt!
}

type RusdVaultBalances @entity
{
  id:                           ID!
  balance0:                     BigInt!
  balance1:                     BigInt!
}